FROM python:3.9-slim-buster

RUN apt-get update \
    && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the requirements.txt file first to leverage Docker layer caching
COPY requirements.txt .
RUN pip3 install --upgrade pip && python3 -m pip install --upgrade setuptools && pip3 install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Copy the Firebase configuration file into the container
COPY kripto-scraper-firebase-adminsdk-i77qf-c5d6bd8cac.json .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "wsgi:app"]
